# This is a basic workflow to help you get started with Actions

name: Gating

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, maint-1.3 ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu:
    # The type of runner that the job will run on
    name: Build and test on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        arch: [aarch64, armv7]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ matrix.arch }}

    # Runs a single command using the runners shell
      run: |
        sudo apt-get update
        sudo env ACCEPT_EULA=Y apt-get upgrade
        sudo apt-get install lcov swig xsltproc rpm-common lua50 libyaml-dev libapt-pkg-dev libdbus-1-dev libdbus-glib-1-dev libcurl4-openssl-dev libgcrypt-dev libselinux1-dev libgconf2-dev libacl1-dev libblkid-dev libcap-dev libxml2-dev libxslt1-dev libxml-parser-perl libxml-xpath-perl libperl-dev librpm-dev librtmp-dev libxmlsec1-dev libxmlsec1-openssl
        sudo apt-get remove rpm

    # Runs a set of commands using the runners shell
    - name: Build
      working-directory: ./build
      run: |
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../
        make all

    - name: Test
      working-directory: ./build
      run: |
        ctest --output-on-failure

  build-fedora:
    name: Build, Test on Fedora Latest (Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Install Deps
      run: dnf install -y cmake git dbus-devel GConf2-devel libacl-devel libblkid-devel libcap-devel libcurl-devel libgcrypt-devel libselinux-devel libxml2-devel libxslt-devel libattr-devel make openldap-devel pcre-devel perl-XML-Parser perl-XML-XPath perl-devel python3-devel rpm-devel swig bzip2-devel gcc-c++ libyaml-devel xmlsec1-devel xmlsec1-openssl-devel hostname bzip2 lua rpm-build which strace
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      working-directory: ./build
      run: |
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../
        make all
    - name: Test
      working-directory: ./build
      run: |
        ctest --output-on-failure

  build-macos:
    # The type of runner that the job will run on
    name: Build, Test on MacOS X Latest
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Deps
      run: |
        brew update
        brew install doxygen
        brew install opendbx
        brew install popt
        brew install swig
        brew install libxmlsec1
        brew install openssl

    # Runs a set of commands using the runners shell
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_PROBES=false ../
        make all

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        echo "Tests are so broken for MacOS :("
